name: image_optimizer
# Image Optimizer docs: https://github.com/calibreapp/image-actions
on:
  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'

concurrency:
  group: image-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image-optimizer:
    name: Image Optimization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          ignorePaths: 'node_modules/**,build'
