name: style_check
on: [pull_request]

jobs:
  vale:
    name: Writing Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Vale Check
        uses: errata-ai/vale-action@reviewdog
        with:
          filter_mode: added
          reporter: github-pr-review
          vale_flags: --glob=*.{md} --minAlertLevel=error
          fail_on_error: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}