name: style_check
on: [pull_request]

jobs:
  vale:
    name: Writing Checks
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: vale
        uses: errata-ai/vale-action@reviewdog
        with:
          version: 2.21.1
          files: __onlyModified
          reporter: github-pr-check
          vale_flags: "--glob=*.{md,mdx}."
          fail_on_error: false
          
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}